### ISSUE TITLE
Problem with Python Dict or Spawn.py Multi Processing

### ISSUE THREAD

**Issue by vysecurity** [s77rt/multicapconverter#5]
```
❯ python3 multicapconverter.py --input ../hashcat-utils-1.8/airportSniffYCMr2h.cap --group-by handshake -x hccapx --all
[i] Networks detected: 40
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/username/Tools/multicapconverter/multicapconverter.py", line 574, in __setitem__
    dict.__setitem__(self, key, {value: 1})
TypeError: unhashable type: 'dict'

Nothing exported. You may want to:
- Try a different export format (-x/--export)
- Use --ignore-ie to ignore ie (AKM Check) (Not Recommended)
```

**Comment by s77rt** [comment]
Can you please attack the cap file as well

**Comment by vysecurity** [comment]
Figured it out, had no handshakes.

**Comment by s77rt** [comment]
This is still a valid issue (bug)
If there is no handshake multicapconverter should simply say so (without raising such error)
Please include the cap file

**Comment by vysecurity** [comment]
I'll try to generate a cap file when I can, but I cannot supply if it has sensitive data 👍🏻

**Comment by s77rt** [comment]
okay, closing this for now (feel free to reopen if needed)
