### ISSUE TITLE
How to get rid of the error?

### ISSUE THREAD

**Issue by paolosezart** [s77rt/multicapconverter#7]
```

D:\Python\38_64\python.exe multicapconverter.py --input OUT.pcapng  --all
[i] Networks detected: 99
[!] Unsupported if_tsresol: 1

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Python\38_64\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Python\38_64\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\VZLOM_WIFI\Caps\convert\multicapconverter.py", line 297, in __setitem__
    dict.__setitem__(self, key, {value: 1})
TypeError: unhashable type: 'dict'

```

What could be the problem? And how to make the script work?

**Comment by s77rt** [comment]
The Unsupported if_tsresol may be related to this. Can you try on another network?

You can also try [capJS](https://s77rt.github.io/capJS/).

**Comment by paolosezart** [comment]
I can send this file to you for analysis. Only I wouldn't want to do it publicly.
